dist: xenial

arch:
  - amd64

os: linux

language: shell

notifications:
  email:
  - team@appwrite.io
  
services:
- docker

before_install:
- curl -fsSL https://get.docker.com | sh
- echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
- mkdir -p $HOME/.docker
- echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
- sudo service docker start
- >
  if [ ! -z "${DOCKERHUB_PULL_USERNAME:-}" ]; then
    echo "${DOCKERHUB_PULL_PASSWORD}" | docker login --username "${DOCKERHUB_PULL_USERNAME}" --password-stdin
  fi
- docker --version
- docker run --rm --privileged linuxkit/binfmt:v0.8
- docker buildx create --use
- chmod -R u+x ./.travis-ci

install:
- COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose up -d
- sleep 10

script:
- docker ps
- docker-compose logs appwrite
- docker-compose logs appwrite-worker-functions
- docker-compose exec appwrite doctor
- docker-compose exec appwrite vars
- docker-compose exec appwrite test --debug

deploy:
  - provider: script
    edge: true
    script: ./.travis-ci/deploy.sh
    on:
      tags: true
  - provider: script
    edge: true
    script: ./.travis-ci/deploy-dev.sh
    on:
      branch: dev

